spring:
    application:
        name:   backend-order-platform

    datasource:
        url:    jdbc:postgresql://localhost:5432/back_end_order_db
        username:   admin
        password:   123456

logging:
    level:
        com.zaxxer.hikari: DEBUG
        org.springframework.jdbc: DEBUG
        org.hibernate.SQL: DEBUG

jwt:
    signerKey: "mPiFx7o9L5S5hohc3pADGBvtfhJTKYwsMWn/Lq0bcdE="
